import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })
type Props = {
  name: string,
}
type card = {
  definition: string,
  value: string
}
export default function Home() {
  const [card, setCard] = useState<card[]>([])
  const [curCard, setCurCard] = useState<card | null>(null)
  const [inputValue, setInputValue] = useState("")
  const [curIndex, setCurIndex] = useState(0)
  const [result, setResult] = useState(false)
  const [isSpoiled, setIsSpoiled] = useState(false);
  const spoilRef = useRef<HTMLSpanElement | null | undefined>(null);
  useEffect(() => {
    const fetch = async () => {
      const data = await axios.get("http://localhost:3000/api/card")
      console.log(data)
      setCard(prev => data.data)
      setCurCard(data?.data[curIndex])
    }
    fetch()
  }, [])

  useEffect(() => {

  })
  const check = () => {
    setIsSpoiled(false)

    if (curCard?.value.trim() == inputValue.trim()) {
      setResult(true)
      if (curIndex == card.length - 1) setCurIndex(0)
      else setCurIndex(prev => prev + 1)
      setInputValue('')
    } else {
      setResult(false)
    }

  }

  const handleKeypress = (e: KeyboardEvent) => {
    if (e.key == 'Enter') {

      setIsSpoiled(false)
      if (curCard?.value.trim() == inputValue.trim()) {
        setResult(true)
        curIndex == (card.length - 1) ? setCurIndex(0) : setCurIndex(prev => prev + 1)
        setInputValue('')
      } else {
        setResult(false)
      }

      if (result) {
        setCurCard(card[curIndex])
      }

    }
  }

  const spoil = () => {
    setIsSpoiled(prev => !prev)
  }
  return (
    <>
      <Head>
        <title>Trang-sama</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black w-full h-screen text-gray-200 flex flex-col items-center">
        <div className="flex flex-col items-center pt-20 w-[50rem] bg-gray-800 mt-40 rounded-md p-8">

          <div className='rounded-md bg-white/20 w-7/12 p-4 text-center mb-20'>
            <span className='text-2xl'>{card[curIndex]?.definition}</span>
          </div>
          <div>
            <input placeholder='text' value={inputValue} onKeyPress={handleKeypress}
              onChange={(e) => setInputValue(e.target.value)} className="rounded-md focus:outline-none bg-white/10 p-2" />
            <button onClick={spoil} className="bg-green-700 p-1 rounded-md ml-4">
              Spoil
            </button>
          </div>
          {isSpoiled &&
            <span className="mt-4 mb-4 h-2 font-bold text-green-600" >
              {card[curIndex]?.value}
            </span>
          }

          <button className="p-2 rounded-md bg-blue-400 mt-4" onClick={check}>check</button>
        </div>
      </main>
    </>
  )
}

